angular.module("www.blocks")
        .config(function ($translateProvider) {
            $translateProvider.translations("en", {
                "": ""
                , "app_label": "Mark Anthony Serrano"
                , "app_label_short": "Mark Serrano"
                , "sitedown": "Site Down"
                , "more_info_message": "Working on it!"
                        // footer
                , "copyleft": "{{ year }} Mark Anthony Mendoza Serrano."
                , "open_source": "All Personal Projects Open Sourced."
                , "license": "Under the Apache License 2.0"
                , "locally_engineered": "Engineered in Watsonville, CA."
                , "title_permission": "See It All"
                , "request_access_pass": "Request a 2-day access key to view my FULL portfolio!"
                , "title_about_me": "Committed to Santa Cruz County"
                , "short_bio": "{{ counting }}+ years fullstack PHP/Javascript. Angular focused. Design inspired. SaltStack. Docker. Proud Banana Slug. Bachelor of Computer Science, UC Santa Cruz."
                , "title_navigation": "Navigation"
                , "email": "Enter Email"
                        // project title
                , "title_cygnus": "Cygnus Management, LLC (2014)"
                , "title_hpl_com": "www.hospitalitypulse.com (2014-2017)"
                , "title_pulsemobile": "pulseMobile (HITEC 2016)"
                , "title_internalc": "Internal Console 2 (2015-2018)"
                , "title_pulsebooker": "pulseBooker Consumer Version (ITB, HITEC 2017)"
                , "title_pulselink": "pulseLink (2018)"
                , "title_pulsebooker_cro": "pulseBooker CRO Version (ITB 2018)"
                , "title_lab": "LAB-MSERRANO"
                , "title_devops": "DevOps"
                , "title_www": "WWW-MSERRANO"
                , "title_docs": "DOCS-MSERRANO"
                        // project description
                , "description_cygnus": "Cygnus Management, LLC. This is a description. This is a description. This is a description. This is a description. "
                , "description_hpl_com": "www.hospitalitypulse.net (2014-2017). This is a description. This is a description. This is a description. This is a description. "
                , "description_pulsemobile": "pulseMobile. This is a description. This is a description. This is a description. This is a description. "
                , "description_internalc": "Internal Console 2 (2015-2018). This is a description. This is a description. This is a description. This is a description. This is a description. "
                , "description_pulsebooker": "pulseBooker Consumer Version. This is a description. This is a description. This is a description. This is a description. This is a description. "
                , "description_pulselink": "pulseLink (2018). This is a description. This is a description. This is a description. This is a description. This is a description. "
                , "description_pulsebooker_cro": "pulseBooker Central Reservation Office (CRO). This is a description. This is a description. This is a description. This is a description. This is a description. This is a description. "
                , "description_lab": "LAB-MSERRANO. This is a description. This is a description. This is a description. "
                , "description_devops": "DevOps. This is a description. This is a description. This is a description. "
                , "description_www": "WWW-MSERRANO. This is a description. This is a description. This is a description. "
                , "description_docs": "DOCS-MSERRANO. This is a description. This is a description. This is a description. "
            });
        });
