angular.module("www.blocks")
        .config(function ($translateProvider) {
            $translateProvider.translations("en", {
                "": ""
                , "app_label": "Mark Anthony Serrano"
                , "app_label_short": "Mark Serrano"
                , "sitedown": "Site Down"
                , "more_info_message": "Working on it!"
                , "not_available_yet": "Not yet available"
                        // footer
                , "copyleft": "{{ year }} Mark Anthony Mendoza Serrano."
                , "open_source": "All Personal Projects Open Sourced."
                , "license": "Under the Apache License 2.0"
                , "locally_engineered": "Engineered in Watsonville, CA."
                , "title_permission": "See It All"
                , "request_access_pass": "Request a 2-day access key to view my FULL portfolio!"
                , "title_about_me": "Committed to Santa Cruz County"
                , "short_bio": "{{ counting }}+ years fullstack PHP/Javascript. Angular focused. Design inspired. SaltStack. Docker. Proud Banana Slug. Bachelor of Computer Science, UC Santa Cruz."
                , "title_navigation": "Navigation"
                , "email": "Enter Email"
                        // project
                , "public_userfacing": "View what is public"
                , "locked_next_step": "Did you receive your activation email?"
                , "title_cygnus": "Cygnus Management, LLC (2014)"
                , "title_hpl_com": "hospitalityPulse, inc (2014-2017)"
                , "title_pulsemobile": "pulseMobile (HITEC 2016)"
                , "title_internalc": "Internal Console 2 (2015-2018)"
                , "title_pulsebooker": "pulseBooker Consumer Version (ITB, HITEC 2017)"
                , "title_pulselink": "pulseLink (2018)"
                , "title_pulsebooker_cro": "pulseBooker CRO Version (ITB 2018)"
                , "title_lab": "LAB-MSERRANO"
                , "title_devops": "DevOps"
                , "title_www": "WWW-MSERRANO"
                , "title_docs": "DOCS-MSERRANO"
                        // project description
                , "description_cygnus": "A company website for Cygnus Management, LLC. After graduating I made a userfacing website for this young company serving the Bay Area. It uses Python [Django], JavaScript [AngularJS], and CSS3 (BootStrap)."
                , "description_hpl_com": "A website for hospitalityPulse, inc. After getting my first job and making a few UI pages for them, they gave me project ownership over their corporate website at www.hospitalitypulse.com. I maintained it from late 2014 to early 2018."
                , "description_pulsemobile": "HITEC is an annual convention just for hotel technology. Working for a bleeding edge tech startup in the hotel industry, we needed to have presence there. In 2016 I helped by creating a quick demo for mobile devices, demonstrating mobile check-in. It was used in a CGI video."
                , "description_internalc": "An internal tool used to facilitate research into issues and produce insights. Essentially a UI to their main database. As I re-designed their corporate website, I was given project ownership of this in-house tool. Starting out small, it became indespensible over the years."
                , "description_pulsebooker": "In addition to HITEC, there is ITB Berlin (the world's leading travel trade show). After a pivot to distribution with the creation of FIRE, we needed to demonstrate the new system's capabilities. This demo is an internet booking engine capable of attribute-based selling."
                , "description_pulselink": "With senior coworkers leaving and the success of pulseBooker, I was promoted to Senior Software Engineer. I was given project ownership over a re-design of pulseLink, an extension of our main product on operations. It is unit tested and supports IE8+."
                , "description_pulsebooker_cro": "This year round we created a version of pulseBooker geared toward the Central Reservation Office. This is the demo made for ITB 2018. The idea is to seamlessly switch between attribute-based and category-based shopping."
                , "description_lab": "Contains the seed for frontend apps of the mserrano-dev organization. Features a WebPack + Node.js build process, a custom made PHP test runner, coverage reporting, and SASS unit tests!"
                , "description_devops": "This project contains configuration management via infrastructure as code and a set of deployment tools for the devs of my organization. Features continuous integration tools via SaltStack/Docker and HAProxy load balancing!"
                , "description_www": "This is my portfolio website. Encapsulates all the good practices I have learned so far. Features caching, unit tests, and readable, re-usable code. Not to mention sweet animations!"
            });
        });
